apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redhatstatuses.redhatstatus.io
spec:
  group: redhatstatus.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  description: "Number of monitoring instances to run."
                  default: 1
                mode:
                  type: string
                  description: "The mode to run the checker in (e.g., watch, web, exporter)."
                  enum: ["watch", "web", "exporter"]
                  default: "watch"
                watchSeconds:
                  type: integer
                  description: "Refresh interval in seconds for watch mode."
                  default: 60
                exporterEnabled:
                  type: boolean
                  description: "Enable the Prometheus exporter."
                  default: true
                exporterPort:
                  type: integer
                  description: "Port for the Prometheus exporter."
                  default: 8000
                webUIEnabled:
                  type: boolean
                  description: "Enable the Flask Web UI."
                  default: false
                webUIPort:
                  type: integer
                  description: "Port for the Web UI."
                  default: 5000
                config:
                  type: object
                  description: "Inline configuration that overrides the default config.json."
                  x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: redhatstatuses
    singular: redhatstatus
    kind: RedHatStatus
    shortNames:
    - rhs
